[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build --filter=@streaming-app/api"]

[start]
cmd = "npm run start:prod --filter=@streaming-app/api"

[deploy]
path = "apps/api"
